# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20190814_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'vip用户'), (2, 'svip用户')], default=0),
        ),
    ]
