# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
