# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_userarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='content',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
